[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.18.0",
    "aiohttp>=3.11.13",
    "coloredlogs>=15.0.1",
    "flask>=3.1.0",
    "lxml>=5.3.1",
    "python-telegram-bot>=21.11.1",
]
